### ISSUE TITLE
Italic is enemy

### ISSUE THREAD

**Issue by wipe2238** [emso-c/pekofy-bot#5]
Looks that automated rabbit cannot exactly handle italic and does some silly stuff when it's present in text.

---

normal _italic?!_

becomes

normal _italic peko_?! peko

NOTE: italic must be closed after `?!` for bug to happen; if it's closed before, everything works correctly.

---

normal "_italic1_", "_italic2_", "_italic3_".

becomes

normal "_italic1_", "_italic2_", "_italic3_ peko".

NOTE: This one feels like it's more related to `"` as i'd really expect [ normal "_italic1_", "_italic2_", "_italic3_" peko. ] in this scenario.

---

_...italic..._
(italic starts before / ends after dots)

becomes

\_ peko...normal peko...\_ peko
(italic is completely lost)

---

Yes, i realize everything above is edge cases :S

**Comment by emso-c** [comment]
Indeed any formatting is enemy (LuKnights rise up!), but I think it'd be easier if you directed me to the instances that didn't work as I couldn't reproduce the bug with the given conditions.

`pekofy("normal *italic?!*")`  
_returns_: "normal \*italic peko?!*"

`pekofy("*...italic...*")`  
_returns_: "\*...italic peko...*"

`pekofy("text *...italic...* text")`  
_returns_: "text peko \*...italic peko...* text peko"

As for your second example, it can't be helped for now since it'd probably require a lot more complex algorithm to solve that issue, in fact, the older pekofication process I made (which is now replaced by @thennal10's much more stable algorithm) was capable of doing that, but it eventually became so unnecessarily complex that it was almost unmaintainable. You can check the first commit to see it.

**Comment by wipe2238** [comment]
Funny enough, all of it can be found in a [single comment](https://www.reddit.com/comments/mfwhwe/-/gsqpt3n/). Italic is done with `_text_` instead of `*text*` which might be a reason why you couldn't reproduce it.

**Comment by thennal10** [comment]
yep, your expected output on example 2 is kind of impossible for the current algorithm. pretty mild edge case though
